-- Global Energie / Global Energie - Full database installer
-- Updated 2026-06-26: full tenancy indexes, fast login indexes, schema metadata cache.
-- One single SQL file: multi-tenancy + application RLS + real relational columns.
-- Import this file in phpMyAdmin / MySQL after selecting your database.
-- For XAMPP, create database `spix` first or uncomment these two lines:
-- CREATE DATABASE IF NOT EXISTS `spix` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE `spix`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `ge_tenants` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `slug` VARCHAR(90) NOT NULL UNIQUE,
  `name` VARCHAR(190) NOT NULL,
  `company_size` VARCHAR(20) NULL,
  `business_email` VARCHAR(190) NULL,
  `phone` VARCHAR(60) NULL,
  `country` VARCHAR(120) NULL,
  `city` VARCHAR(120) NULL,
  `zip` VARCHAR(40) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_tenant_status` (`status`),
  KEY `idx_tenant_email` (`business_email`),
  KEY `idx_tenant_city` (`city`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `procrm_audit_logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `user_id` INT NULL,
  `username` VARCHAR(120) NULL,
  `action` VARCHAR(120) NOT NULL,
  `details` TEXT NULL,
  `ip` VARCHAR(80) NULL,
  `user_agent` VARCHAR(255) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_created` (`created_at`),
  KEY `idx_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_schema_meta` (
  `meta_key` VARCHAR(90) NOT NULL PRIMARY KEY,
  `meta_value` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: users
CREATE TABLE IF NOT EXISTS `ge_users` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `civility` VARCHAR(90) NULL,
  `name` VARCHAR(190) NULL,
  `firstname` VARCHAR(190) NULL,
  `username` VARCHAR(190) NULL,
  `gender` VARCHAR(90) NULL,
  `employee` TINYINT(1) NOT NULL DEFAULT 0,
  `manager_id` INT NULL,
  `expense_validator` VARCHAR(90) NULL,
  `external_user` VARCHAR(90) NULL,
  `valid_from` VARCHAR(40) NULL,
  `valid_to` VARCHAR(40) NULL,
  `address` TEXT NULL,
  `zip` VARCHAR(90) NULL,
  `city` VARCHAR(120) NULL,
  `country` VARCHAR(120) NULL,
  `state` VARCHAR(120) NULL,
  `phone` VARCHAR(120) NULL,
  `mobile` VARCHAR(120) NULL,
  `fax` VARCHAR(120) NULL,
  `email` VARCHAR(190) NULL,
  `signature` TEXT NULL,
  `note_public` TEXT NULL,
  `note_private` TEXT NULL,
  `job` VARCHAR(190) NULL,
  `weekly_hours` VARCHAR(90) NULL,
  `hire_date` VARCHAR(40) NULL,
  `birth_date` VARCHAR(40) NULL,
  `salary` VARCHAR(90) NULL,
  `hourly_rate` VARCHAR(90) NULL,
  `daily_rate` VARCHAR(90) NULL,
  `company` VARCHAR(190) NULL,
  `role` VARCHAR(120) NULL,
  `password` VARCHAR(255) NULL,
  `force_password_change` TINYINT(1) NOT NULL DEFAULT 0,
  `profile_picture` VARCHAR(255) NULL,
  `twofa_secret` VARCHAR(190) NULL,
  `twofa_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `last_login` VARCHAR(40) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_users_name` (`name`),
  KEY `idx_ge_users_username` (`username`),
  KEY `idx_ge_users_email` (`email`),
  KEY `idx_ge_users_tenant_email_status` (`tenant_id`, `email`, `status`),
  KEY `idx_ge_users_tenant_username_status` (`tenant_id`, `username`, `status`),
  KEY `idx_ge_users_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: warehouses
CREATE TABLE IF NOT EXISTS `ge_warehouses` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(190) NULL,
  `parent_id` INT NULL,
  `description` TEXT NULL,
  `address` TEXT NULL,
  `zip` VARCHAR(90) NULL,
  `city` VARCHAR(120) NULL,
  `country` VARCHAR(120) NULL,
  `phone` VARCHAR(120) NULL,
  `fax` VARCHAR(120) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_warehouses_name` (`name`),
  KEY `idx_ge_warehouses_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: warehouse_movements
CREATE TABLE IF NOT EXISTS `ge_warehouse_movements` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `warehouse_id` INT NULL,
  `warehouse_name` VARCHAR(190) NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `type` VARCHAR(90) NULL,
  `movement_type` VARCHAR(90) NULL,
  `source_type` VARCHAR(90) NULL,
  `source_id` INT NULL,
  `note` TEXT NULL,
  `date` VARCHAR(40) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_warehouse_movements_warehouse_id` (`warehouse_id`),
  KEY `idx_ge_warehouse_movements_product_id` (`product_id`),
  KEY `idx_ge_warehouse_movements_type` (`type`),
  KEY `idx_ge_warehouse_movements_date` (`date`),
  KEY `idx_ge_warehouse_movements_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: settings
CREATE TABLE IF NOT EXISTS `ge_settings` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `company_name` VARCHAR(190) NULL,
  `language` VARCHAR(90) NULL,
  `currency` VARCHAR(90) NULL,
  `timezone` VARCHAR(120) NULL,
  `api_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `api_key_hash` VARCHAR(190) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_settings_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: products
CREATE TABLE IF NOT EXISTS `ge_products` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sale_status` VARCHAR(90) NULL,
  `buy_status` VARCHAR(90) NULL,
  `description` TEXT NULL,
  `public_url` VARCHAR(255) NULL,
  `site_visible` VARCHAR(90) NULL,
  `warehouse` VARCHAR(190) NULL,
  `warehouse_id` INT NULL,
  `alert_stock` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `desired_stock` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `type` VARCHAR(120) NULL,
  `product_type` VARCHAR(120) NULL,
  `weight` VARCHAR(90) NULL,
  `length` VARCHAR(90) NULL,
  `width` VARCHAR(90) NULL,
  `height` VARCHAR(90) NULL,
  `surface` VARCHAR(90) NULL,
  `volume` VARCHAR(90) NULL,
  `unit` VARCHAR(90) NULL,
  `customs_code` VARCHAR(120) NULL,
  `country` VARCHAR(120) NULL,
  `note` TEXT NULL,
  `sale_price` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `sale_tax_mode` VARCHAR(90) NULL,
  `min_sale_price` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `tax` VARCHAR(90) NULL,
  `tax_rate` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `vat` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `buy_price` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `physical_stock` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `stock` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `virtual_stock` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_products_warehouse_id` (`warehouse_id`),
  KEY `idx_ge_products_type` (`type`),
  KEY `idx_ge_products_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: tiers
CREATE TABLE IF NOT EXISTS `ge_tiers` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `type` VARCHAR(90) NULL,
  `is_prospect` TINYINT(1) NOT NULL DEFAULT 0,
  `is_client` TINYINT(1) NOT NULL DEFAULT 0,
  `is_supplier` TINYINT(1) NOT NULL DEFAULT 0,
  `name` VARCHAR(190) NULL,
  `alias` VARCHAR(190) NULL,
  `code` VARCHAR(90) NULL,
  `code_client` VARCHAR(90) NULL,
  `code_supplier` VARCHAR(90) NULL,
  `address` TEXT NULL,
  `zip` VARCHAR(90) NULL,
  `city` VARCHAR(120) NULL,
  `country` VARCHAR(120) NULL,
  `state` VARCHAR(120) NULL,
  `phone` VARCHAR(120) NULL,
  `mobile` VARCHAR(120) NULL,
  `fax` VARCHAR(120) NULL,
  `web` VARCHAR(190) NULL,
  `email` VARCHAR(190) NULL,
  `rc` VARCHAR(90) NULL,
  `patente` VARCHAR(90) NULL,
  `tax_id` VARCHAR(90) NULL,
  `cnss` VARCHAR(90) NULL,
  `ice` VARCHAR(90) NULL,
  `vat_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `vat_number` VARCHAR(90) NULL,
  `euid` VARCHAR(120) NULL,
  `tier_type` VARCHAR(120) NULL,
  `legal_form` VARCHAR(120) NULL,
  `created_company` VARCHAR(90) NULL,
  `capital` VARCHAR(90) NULL,
  `staff_size` VARCHAR(90) NULL,
  `payment_terms` VARCHAR(120) NULL,
  `payment_mode` VARCHAR(120) NULL,
  `parent_company` VARCHAR(190) NULL,
  `owner` VARCHAR(190) NULL,
  `logo` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_tiers_name` (`name`),
  KEY `idx_ge_tiers_type` (`type`),
  KEY `idx_ge_tiers_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: clients
CREATE TABLE IF NOT EXISTS `ge_clients` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `type` VARCHAR(90) NULL,
  `is_prospect` TINYINT(1) NOT NULL DEFAULT 0,
  `is_client` TINYINT(1) NOT NULL DEFAULT 0,
  `is_supplier` TINYINT(1) NOT NULL DEFAULT 0,
  `name` VARCHAR(190) NULL,
  `alias` VARCHAR(190) NULL,
  `code` VARCHAR(90) NULL,
  `code_client` VARCHAR(90) NULL,
  `code_supplier` VARCHAR(90) NULL,
  `address` TEXT NULL,
  `zip` VARCHAR(90) NULL,
  `city` VARCHAR(120) NULL,
  `country` VARCHAR(120) NULL,
  `state` VARCHAR(120) NULL,
  `phone` VARCHAR(120) NULL,
  `mobile` VARCHAR(120) NULL,
  `fax` VARCHAR(120) NULL,
  `web` VARCHAR(190) NULL,
  `email` VARCHAR(190) NULL,
  `rc` VARCHAR(90) NULL,
  `patente` VARCHAR(90) NULL,
  `tax_id` VARCHAR(90) NULL,
  `cnss` VARCHAR(90) NULL,
  `ice` VARCHAR(90) NULL,
  `vat_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `vat_number` VARCHAR(90) NULL,
  `euid` VARCHAR(120) NULL,
  `tier_type` VARCHAR(120) NULL,
  `legal_form` VARCHAR(120) NULL,
  `created_company` VARCHAR(90) NULL,
  `capital` VARCHAR(90) NULL,
  `staff_size` VARCHAR(90) NULL,
  `payment_terms` VARCHAR(120) NULL,
  `payment_mode` VARCHAR(120) NULL,
  `parent_company` VARCHAR(190) NULL,
  `owner` VARCHAR(190) NULL,
  `logo` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_clients_name` (`name`),
  KEY `idx_ge_clients_type` (`type`),
  KEY `idx_ge_clients_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: suppliers
CREATE TABLE IF NOT EXISTS `ge_suppliers` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `type` VARCHAR(90) NULL,
  `is_prospect` TINYINT(1) NOT NULL DEFAULT 0,
  `is_client` TINYINT(1) NOT NULL DEFAULT 0,
  `is_supplier` TINYINT(1) NOT NULL DEFAULT 0,
  `name` VARCHAR(190) NULL,
  `alias` VARCHAR(190) NULL,
  `code` VARCHAR(90) NULL,
  `code_client` VARCHAR(90) NULL,
  `code_supplier` VARCHAR(90) NULL,
  `address` TEXT NULL,
  `zip` VARCHAR(90) NULL,
  `city` VARCHAR(120) NULL,
  `country` VARCHAR(120) NULL,
  `state` VARCHAR(120) NULL,
  `phone` VARCHAR(120) NULL,
  `mobile` VARCHAR(120) NULL,
  `fax` VARCHAR(120) NULL,
  `web` VARCHAR(190) NULL,
  `email` VARCHAR(190) NULL,
  `rc` VARCHAR(90) NULL,
  `patente` VARCHAR(90) NULL,
  `tax_id` VARCHAR(90) NULL,
  `cnss` VARCHAR(90) NULL,
  `ice` VARCHAR(90) NULL,
  `vat_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `vat_number` VARCHAR(90) NULL,
  `euid` VARCHAR(120) NULL,
  `tier_type` VARCHAR(120) NULL,
  `legal_form` VARCHAR(120) NULL,
  `created_company` VARCHAR(90) NULL,
  `capital` VARCHAR(90) NULL,
  `staff_size` VARCHAR(90) NULL,
  `payment_terms` VARCHAR(120) NULL,
  `payment_mode` VARCHAR(120) NULL,
  `parent_company` VARCHAR(190) NULL,
  `owner` VARCHAR(190) NULL,
  `logo` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_suppliers_name` (`name`),
  KEY `idx_ge_suppliers_type` (`type`),
  KEY `idx_ge_suppliers_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: quotes
CREATE TABLE IF NOT EXISTS `ge_quotes` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `client_id` INT NULL,
  `client_ref` VARCHAR(90) NULL,
  `client` VARCHAR(190) NULL,
  `proposal_date` VARCHAR(40) NULL,
  `validity` VARCHAR(90) NULL,
  `end_date` VARCHAR(40) NULL,
  `payment_terms` VARCHAR(120) NULL,
  `payment_mode` VARCHAR(120) NULL,
  `origin` VARCHAR(120) NULL,
  `delivery_delay` VARCHAR(120) NULL,
  `shipping_method` VARCHAR(120) NULL,
  `delivery_date` VARCHAR(40) NULL,
  `template` VARCHAR(120) NULL,
  `public_note` TEXT NULL,
  `private_note` TEXT NULL,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `author` VARCHAR(190) NULL,
  `author_id` INT NULL,
  `author_username` VARCHAR(190) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_quotes_client` (`client`),
  KEY `idx_ge_quotes_client_id` (`client_id`),
  KEY `idx_ge_quotes_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: quote_lines
CREATE TABLE IF NOT EXISTS `ge_quote_lines` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `quote_id` INT NULL,
  `line_no` INT NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `description` TEXT NULL,
  `tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `pu_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(90) NULL,
  `reduction` VARCHAR(90) NULL,
  `cost_price` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_quote_lines_product_id` (`product_id`),
  KEY `idx_ge_quote_lines_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: quote_documents
CREATE TABLE IF NOT EXISTS `ge_quote_documents` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `quote_id` INT NULL,
  `filename` VARCHAR(255) NULL,
  `original_name` VARCHAR(255) NULL,
  `mime_type` VARCHAR(120) NULL,
  `size_bytes` BIGINT NULL,
  `url` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_quote_documents_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: quote_emails
CREATE TABLE IF NOT EXISTS `ge_quote_emails` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `quote_id` INT NULL,
  `to_email` VARCHAR(190) NULL,
  `cc` VARCHAR(190) NULL,
  `subject` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `sent` TINYINT(1) NOT NULL DEFAULT 0,
  `error` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_quote_emails_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: orders
CREATE TABLE IF NOT EXISTS `ge_orders` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `client_id` INT NULL,
  `client_ref` VARCHAR(90) NULL,
  `client` VARCHAR(190) NULL,
  `order_date` VARCHAR(40) NULL,
  `delivery_date` VARCHAR(40) NULL,
  `delivery_delay` VARCHAR(120) NULL,
  `payment_terms` VARCHAR(120) NULL,
  `payment_mode` VARCHAR(120) NULL,
  `shipping_method` VARCHAR(120) NULL,
  `channel` VARCHAR(120) NULL,
  `template` VARCHAR(120) NULL,
  `public_note` TEXT NULL,
  `private_note` TEXT NULL,
  `expediable` VARCHAR(90) NULL,
  `facture` VARCHAR(90) NULL,
  `delivery_status` VARCHAR(90) NULL,
  `invoice_id` INT NULL,
  `invoice_ref` VARCHAR(90) NULL,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `author` VARCHAR(190) NULL,
  `author_id` INT NULL,
  `author_username` VARCHAR(190) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_orders_client` (`client`),
  KEY `idx_ge_orders_client_id` (`client_id`),
  KEY `idx_ge_orders_order_date` (`order_date`),
  KEY `idx_ge_orders_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: order_lines
CREATE TABLE IF NOT EXISTS `ge_order_lines` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order_id` INT NULL,
  `line_no` INT NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `description` TEXT NULL,
  `tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `pu_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(90) NULL,
  `reduction` VARCHAR(90) NULL,
  `cost_price` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_order_lines_product_id` (`product_id`),
  KEY `idx_ge_order_lines_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: order_documents
CREATE TABLE IF NOT EXISTS `ge_order_documents` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order_id` INT NULL,
  `filename` VARCHAR(255) NULL,
  `original_name` VARCHAR(255) NULL,
  `mime_type` VARCHAR(120) NULL,
  `size_bytes` BIGINT NULL,
  `url` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_order_documents_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: order_emails
CREATE TABLE IF NOT EXISTS `ge_order_emails` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order_id` INT NULL,
  `to_email` VARCHAR(190) NULL,
  `cc` VARCHAR(190) NULL,
  `subject` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `sent` TINYINT(1) NOT NULL DEFAULT 0,
  `error` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_order_emails_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: invoices
CREATE TABLE IF NOT EXISTS `ge_invoices` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `client_id` INT NULL,
  `client_ref` VARCHAR(90) NULL,
  `client` VARCHAR(190) NULL,
  `type` VARCHAR(120) NULL,
  `invoice_date` VARCHAR(40) NULL,
  `due_date` VARCHAR(40) NULL,
  `payment_terms` VARCHAR(120) NULL,
  `payment_mode` VARCHAR(120) NULL,
  `bank_account` VARCHAR(120) NULL,
  `template` VARCHAR(120) NULL,
  `public_note` TEXT NULL,
  `private_note` TEXT NULL,
  `order_id` INT NULL,
  `order_ref` VARCHAR(90) NULL,
  `expedition_id` INT NULL,
  `expedition_ref` VARCHAR(90) NULL,
  `paid_amount` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `remaining_amount` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `created_by` VARCHAR(190) NULL,
  `created_by_id` INT NULL,
  `created_by_username` VARCHAR(190) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_invoices_client` (`client`),
  KEY `idx_ge_invoices_client_id` (`client_id`),
  KEY `idx_ge_invoices_type` (`type`),
  KEY `idx_ge_invoices_invoice_date` (`invoice_date`),
  KEY `idx_ge_invoices_due_date` (`due_date`),
  KEY `idx_ge_invoices_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: invoice_lines
CREATE TABLE IF NOT EXISTS `ge_invoice_lines` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `invoice_id` INT NULL,
  `line_no` INT NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `description` TEXT NULL,
  `tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `pu_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(90) NULL,
  `reduction` VARCHAR(90) NULL,
  `cost_price` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_invoice_lines_product_id` (`product_id`),
  KEY `idx_ge_invoice_lines_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: invoice_documents
CREATE TABLE IF NOT EXISTS `ge_invoice_documents` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `invoice_id` INT NULL,
  `filename` VARCHAR(255) NULL,
  `original_name` VARCHAR(255) NULL,
  `mime_type` VARCHAR(120) NULL,
  `size_bytes` BIGINT NULL,
  `url` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_invoice_documents_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: invoice_payments
CREATE TABLE IF NOT EXISTS `ge_invoice_payments` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `invoice_id` INT NULL,
  `date` VARCHAR(40) NULL,
  `mode` VARCHAR(120) NULL,
  `reference` VARCHAR(190) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_invoice_payments_date` (`date`),
  KEY `idx_ge_invoice_payments_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: invoice_emails
CREATE TABLE IF NOT EXISTS `ge_invoice_emails` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `invoice_id` INT NULL,
  `to_email` VARCHAR(190) NULL,
  `cc` VARCHAR(190) NULL,
  `subject` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `sent` TINYINT(1) NOT NULL DEFAULT 0,
  `error` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_invoice_emails_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: expeditions
CREATE TABLE IF NOT EXISTS `ge_expeditions` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order_id` INT NULL,
  `order_ref` VARCHAR(90) NULL,
  `tier_id` INT NULL,
  `tier_name` VARCHAR(190) NULL,
  `tier_ref` VARCHAR(90) NULL,
  `city` VARCHAR(120) NULL,
  `zip` VARCHAR(90) NULL,
  `warehouse_id` INT NULL,
  `warehouse_name` VARCHAR(190) NULL,
  `date` VARCHAR(40) NULL,
  `delivery_date` VARCHAR(40) NULL,
  `shipping_method` VARCHAR(120) NULL,
  `tracking` VARCHAR(190) NULL,
  `note_public` TEXT NULL,
  `invoice_id` INT NULL,
  `invoice_ref` VARCHAR(90) NULL,
  `created_by` VARCHAR(190) NULL,
  `created_by_id` INT NULL,
  `created_by_username` VARCHAR(190) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_expeditions_tier_id` (`tier_id`),
  KEY `idx_ge_expeditions_warehouse_id` (`warehouse_id`),
  KEY `idx_ge_expeditions_date` (`date`),
  KEY `idx_ge_expeditions_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: expedition_lines
CREATE TABLE IF NOT EXISTS `ge_expedition_lines` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expedition_id` INT NULL,
  `line_no` INT NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(90) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_expedition_lines_product_id` (`product_id`),
  KEY `idx_ge_expedition_lines_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: expedition_documents
CREATE TABLE IF NOT EXISTS `ge_expedition_documents` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expedition_id` INT NULL,
  `filename` VARCHAR(255) NULL,
  `original_name` VARCHAR(255) NULL,
  `mime_type` VARCHAR(120) NULL,
  `size_bytes` BIGINT NULL,
  `url` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_expedition_documents_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: receptions
CREATE TABLE IF NOT EXISTS `ge_receptions` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tier_id` INT NULL,
  `tier_name` VARCHAR(190) NULL,
  `warehouse_id` INT NULL,
  `warehouse_name` VARCHAR(190) NULL,
  `date` VARCHAR(40) NULL,
  `order_date` VARCHAR(40) NULL,
  `method` VARCHAR(120) NULL,
  `supplier_doc` VARCHAR(190) NULL,
  `note_public` TEXT NULL,
  `created_by` VARCHAR(190) NULL,
  `created_by_id` INT NULL,
  `created_by_username` VARCHAR(190) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_receptions_tier_id` (`tier_id`),
  KEY `idx_ge_receptions_warehouse_id` (`warehouse_id`),
  KEY `idx_ge_receptions_date` (`date`),
  KEY `idx_ge_receptions_order_date` (`order_date`),
  KEY `idx_ge_receptions_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: reception_lines
CREATE TABLE IF NOT EXISTS `ge_reception_lines` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `reception_id` INT NULL,
  `line_no` INT NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(90) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_reception_lines_product_id` (`product_id`),
  KEY `idx_ge_reception_lines_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: reception_documents
CREATE TABLE IF NOT EXISTS `ge_reception_documents` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `reception_id` INT NULL,
  `filename` VARCHAR(255) NULL,
  `original_name` VARCHAR(255) NULL,
  `mime_type` VARCHAR(120) NULL,
  `size_bytes` BIGINT NULL,
  `url` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_reception_documents_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: sent_emails
CREATE TABLE IF NOT EXISTS `ge_sent_emails` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `type` VARCHAR(90) NULL,
  `object_id` INT NULL,
  `to_email` VARCHAR(190) NULL,
  `cc` VARCHAR(190) NULL,
  `subject` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `sent` TINYINT(1) NOT NULL DEFAULT 0,
  `error` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_sent_emails_type` (`type`),
  KEY `idx_ge_sent_emails_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: signatures
CREATE TABLE IF NOT EXISTS `ge_signatures` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `token_hash` VARCHAR(255) NULL,
  `public_url` VARCHAR(255) NULL,
  `pdf_file` VARCHAR(255) NULL,
  `pdf_name` VARCHAR(190) NULL,
  `doc_type` VARCHAR(120) NULL,
  `client_name` VARCHAR(190) NULL,
  `client_email` VARCHAR(190) NULL,
  `cc_email` VARCHAR(190) NULL,
  `subject` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `created_by` INT NULL,
  `created_by_name` VARCHAR(190) NULL,
  `expires_at` VARCHAR(40) NULL,
  `sent_at` VARCHAR(40) NULL,
  `opened_at` VARCHAR(40) NULL,
  `signed_at` VARCHAR(40) NULL,
  `signer_name` VARCHAR(190) NULL,
  `signer_email` VARCHAR(190) NULL,
  `signature_data` LONGTEXT NULL,
  `signed_ip_hash` VARCHAR(255) NULL,
  `signed_user_agent` VARCHAR(255) NULL,
  `signed_pdf_file` VARCHAR(255) NULL,
  `email_sent` TINYINT(1) NOT NULL DEFAULT 0,
  `email_error` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_signatures_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: stock_alerts
CREATE TABLE IF NOT EXISTS `ge_stock_alerts` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `warehouse_id` INT NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `threshold` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `last_notified_at` VARCHAR(40) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_stock_alerts_warehouse_id` (`warehouse_id`),
  KEY `idx_ge_stock_alerts_product_id` (`product_id`),
  KEY `idx_ge_stock_alerts_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: user_emails
CREATE TABLE IF NOT EXISTS `ge_user_emails` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT NULL,
  `to_email` VARCHAR(190) NULL,
  `cc` VARCHAR(190) NULL,
  `subject` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `sent` TINYINT(1) NOT NULL DEFAULT 0,
  `error` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_user_emails_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: password_resets
CREATE TABLE IF NOT EXISTS `ge_password_resets` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT NULL,
  `email` VARCHAR(190) NULL,
  `token_hash` VARCHAR(255) NULL,
  `expires_at` VARCHAR(40) NULL,
  `used` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_password_resets_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: login_attempts
CREATE TABLE IF NOT EXISTS `ge_login_attempts` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `bucket` VARCHAR(90) NULL,
  `login_hash` VARCHAR(90) NULL,
  `ip_hash` VARCHAR(90) NULL,
  `count` INT NOT NULL DEFAULT 0,
  `first` INT NOT NULL DEFAULT 0,
  `locked_until` INT NOT NULL DEFAULT 0,
  `updated_at_ts` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`tenant_id`, `record_id`),
  UNIQUE KEY `uniq_ge_login_attempts_bucket` (`tenant_id`, `bucket`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ge_login_attempts_login_hash` (`login_hash`),
  KEY `idx_ge_login_attempts_ip_hash` (`ip_hash`),
  KEY `idx_ge_login_attempts_locked` (`tenant_id`, `locked_until`, `updated_at_ts`),
  KEY `idx_ge_login_attempts_updated` (`updated_at_ts`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: bank_accounts
CREATE TABLE IF NOT EXISTS `ge_bank_accounts` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(190) NULL,
  `bank_name` VARCHAR(190) NULL,
  `iban` VARCHAR(190) NULL,
  `rib` VARCHAR(190) NULL,
  `currency` VARCHAR(90) NULL,
  `opening_balance` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `current_balance` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_bank_accounts_name` (`name`),
  KEY `idx_ge_bank_accounts_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: payment_modes
CREATE TABLE IF NOT EXISTS `ge_payment_modes` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(190) NULL,
  `type` VARCHAR(120) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_payment_modes_name` (`name`),
  KEY `idx_ge_payment_modes_type` (`type`),
  KEY `idx_ge_payment_modes_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: payments
CREATE TABLE IF NOT EXISTS `ge_payments` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `invoice_id` INT NULL,
  `invoice_ref` VARCHAR(90) NULL,
  `client_id` INT NULL,
  `client_name` VARCHAR(190) NULL,
  `bank_account_id` INT NULL,
  `date` VARCHAR(40) NULL,
  `mode` VARCHAR(120) NULL,
  `reference` VARCHAR(190) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_payments_client_id` (`client_id`),
  KEY `idx_ge_payments_date` (`date`),
  KEY `idx_ge_payments_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: supplier_payments
CREATE TABLE IF NOT EXISTS `ge_supplier_payments` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `supplier_invoice_id` INT NULL,
  `supplier_invoice_ref` VARCHAR(90) NULL,
  `supplier_id` INT NULL,
  `supplier_name` VARCHAR(190) NULL,
  `bank_account_id` INT NULL,
  `date` VARCHAR(40) NULL,
  `mode` VARCHAR(120) NULL,
  `reference` VARCHAR(190) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_supplier_payments_supplier_id` (`supplier_id`),
  KEY `idx_ge_supplier_payments_date` (`date`),
  KEY `idx_ge_supplier_payments_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: accounting_accounts
CREATE TABLE IF NOT EXISTS `ge_accounting_accounts` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `code` VARCHAR(90) NULL,
  `type` VARCHAR(120) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_accounting_accounts_type` (`type`),
  KEY `idx_ge_accounting_accounts_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: accounting_journals
CREATE TABLE IF NOT EXISTS `ge_accounting_journals` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `code` VARCHAR(90) NULL,
  `type` VARCHAR(120) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_accounting_journals_type` (`type`),
  KEY `idx_ge_accounting_journals_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: accounting_entries
CREATE TABLE IF NOT EXISTS `ge_accounting_entries` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `date` VARCHAR(40) NULL,
  `journal` VARCHAR(90) NULL,
  `account` VARCHAR(90) NULL,
  `debit` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `credit` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `source_type` VARCHAR(120) NULL,
  `source_id` INT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_accounting_entries_date` (`date`),
  KEY `idx_ge_accounting_entries_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: accounting_periods
CREATE TABLE IF NOT EXISTS `ge_accounting_periods` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(190) NULL,
  `start_date` VARCHAR(40) NULL,
  `end_date` VARCHAR(40) NULL,
  `closed_by` INT NULL,
  `closed_at` VARCHAR(40) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_accounting_periods_name` (`name`),
  KEY `idx_ge_accounting_periods_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: currencies
CREATE TABLE IF NOT EXISTS `ge_currencies` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `code` VARCHAR(90) NULL,
  `name` VARCHAR(190) NULL,
  `rate` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `symbol` VARCHAR(90) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_currencies_name` (`name`),
  KEY `idx_ge_currencies_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: custom_fields
CREATE TABLE IF NOT EXISTS `ge_custom_fields` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `object_type` VARCHAR(120) NULL,
  `field_key` VARCHAR(120) NULL,
  `field_type` VARCHAR(120) NULL,
  `required` TINYINT(1) NOT NULL DEFAULT 0,
  `options` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_custom_fields_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: documents
CREATE TABLE IF NOT EXISTS `ge_documents` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `object_type` VARCHAR(120) NULL,
  `object_id` INT NULL,
  `object_ref` VARCHAR(90) NULL,
  `title` VARCHAR(190) NULL,
  `filename` VARCHAR(255) NULL,
  `mime_type` VARCHAR(120) NULL,
  `size_bytes` BIGINT NULL,
  `url` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_documents_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: projects
CREATE TABLE IF NOT EXISTS `ge_projects` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` VARCHAR(190) NULL,
  `client_id` INT NULL,
  `client_name` VARCHAR(190) NULL,
  `start_date` VARCHAR(40) NULL,
  `end_date` VARCHAR(40) NULL,
  `budget` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_projects_client_id` (`client_id`),
  KEY `idx_ge_projects_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: project_tasks
CREATE TABLE IF NOT EXISTS `ge_project_tasks` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `project_id` INT NULL,
  `title` VARCHAR(190) NULL,
  `assigned_to` INT NULL,
  `start_date` VARCHAR(40) NULL,
  `due_date` VARCHAR(40) NULL,
  `estimated_hours` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `spent_hours` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_project_tasks_due_date` (`due_date`),
  KEY `idx_ge_project_tasks_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: agenda_events
CREATE TABLE IF NOT EXISTS `ge_agenda_events` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` VARCHAR(190) NULL,
  `object_type` VARCHAR(120) NULL,
  `object_id` INT NULL,
  `event_date` VARCHAR(40) NULL,
  `event_time` VARCHAR(90) NULL,
  `assigned_to` INT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_agenda_events_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: pos_sales
CREATE TABLE IF NOT EXISTS `ge_pos_sales` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `client_name` VARCHAR(190) NULL,
  `date` VARCHAR(40) NULL,
  `amount_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `payment_mode` VARCHAR(120) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_pos_sales_date` (`date`),
  KEY `idx_ge_pos_sales_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: pos_sale_lines
CREATE TABLE IF NOT EXISTS `ge_pos_sale_lines` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sale_id` INT NULL,
  `line_no` INT NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `pu_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_pos_sale_lines_product_id` (`product_id`),
  KEY `idx_ge_pos_sale_lines_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: manufacturing_orders
CREATE TABLE IF NOT EXISTS `ge_manufacturing_orders` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `start_date` VARCHAR(40) NULL,
  `end_date` VARCHAR(40) NULL,
  `cost` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_manufacturing_orders_product_id` (`product_id`),
  KEY `idx_ge_manufacturing_orders_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: manufacturing_lines
CREATE TABLE IF NOT EXISTS `ge_manufacturing_lines` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `manufacturing_id` INT NULL,
  `line_no` INT NULL,
  `component_id` INT NULL,
  `component_ref` VARCHAR(90) NULL,
  `component_label` VARCHAR(190) NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(90) NULL,
  `cost` DECIMAL(15,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_manufacturing_lines_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: stock_lots
CREATE TABLE IF NOT EXISTS `ge_stock_lots` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `warehouse_id` INT NULL,
  `lot_number` VARCHAR(120) NULL,
  `expiry_date` VARCHAR(40) NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_stock_lots_warehouse_id` (`warehouse_id`),
  KEY `idx_ge_stock_lots_product_id` (`product_id`),
  KEY `idx_ge_stock_lots_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: stock_serials
CREATE TABLE IF NOT EXISTS `ge_stock_serials` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `warehouse_id` INT NULL,
  `serial_number` VARCHAR(190) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_stock_serials_warehouse_id` (`warehouse_id`),
  KEY `idx_ge_stock_serials_product_id` (`product_id`),
  KEY `idx_ge_stock_serials_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: inventories
CREATE TABLE IF NOT EXISTS `ge_inventories` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `warehouse_id` INT NULL,
  `warehouse_name` VARCHAR(190) NULL,
  `date` VARCHAR(40) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_inventories_warehouse_id` (`warehouse_id`),
  KEY `idx_ge_inventories_date` (`date`),
  KEY `idx_ge_inventories_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: inventory_lines
CREATE TABLE IF NOT EXISTS `ge_inventory_lines` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `inventory_id` INT NULL,
  `line_no` INT NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `system_qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `counted_qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `difference_qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(90) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_inventory_lines_product_id` (`product_id`),
  KEY `idx_ge_inventory_lines_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: imports
CREATE TABLE IF NOT EXISTS `ge_imports` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `collection` VARCHAR(120) NULL,
  `filename` VARCHAR(255) NULL,
  `rows_imported` INT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_imports_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: exports
CREATE TABLE IF NOT EXISTS `ge_exports` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `collection` VARCHAR(120) NULL,
  `filename` VARCHAR(255) NULL,
  `rows_exported` INT NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_exports_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Real table for collection: api_tokens
CREATE TABLE IF NOT EXISTS `ge_api_tokens` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `record_id` INT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `extra_json` LONGTEXT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount` DECIMAL(15,3) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(190) NULL,
  `token_hash` VARCHAR(255) NULL,
  `permissions` TEXT NULL,
  `last_used_at` VARCHAR(40) NULL,
  PRIMARY KEY (`tenant_id`, `record_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_ref` (`ref`),
  KEY `idx_label` (`label`),
  KEY `idx_status` (`status`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_ge_api_tokens_name` (`name`),
  KEY `idx_ge_api_tokens_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_structured_products` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `id` INT NOT NULL,
  `ref` VARCHAR(90) NULL,
  `label` VARCHAR(190) NOT NULL,
  `type` VARCHAR(80) NULL,
  `brand` VARCHAR(120) NULL,
  `sale_price` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `buy_price` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `physical_stock` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `virtual_stock` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `alert_stock` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `warehouse_id` INT NULL,
  `status_sale` VARCHAR(80) NULL,
  `status_buy` VARCHAR(80) NULL,
  `site_visible` VARCHAR(20) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(`tenant_id`, `id`),
  KEY `idx_product_ref` (`ref`), KEY `idx_product_label` (`label`), KEY `idx_product_stock` (`physical_stock`), KEY `idx_product_visible` (`site_visible`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_structured_tiers` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `id` INT NOT NULL,
  `ref` VARCHAR(90) NULL,
  `name` VARCHAR(190) NOT NULL,
  `type` VARCHAR(40) NOT NULL DEFAULT 'prospect',
  `email` VARCHAR(190) NULL,
  `phone` VARCHAR(80) NULL,
  `city` VARCHAR(120) NULL,
  `country` VARCHAR(120) NULL,
  `status` VARCHAR(80) NULL,
  `ice` VARCHAR(90) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(`tenant_id`, `id`),
  KEY `idx_tier_ref` (`ref`), KEY `idx_tier_name` (`name`), KEY `idx_tier_type` (`type`), KEY `idx_tier_city` (`city`), KEY `idx_tier_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_structured_sales` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `object_type` VARCHAR(40) NOT NULL,
  `object_id` INT NOT NULL,
  `ref` VARCHAR(90) NULL,
  `tier_id` INT NULL,
  `tier_name` VARCHAR(190) NULL,
  `status` VARCHAR(90) NULL,
  `amount_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `object_date` DATE NULL,
  `due_date` DATE NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(`tenant_id`, `object_type`, `object_id`),
  KEY `idx_sales_ref` (`ref`), KEY `idx_sales_tier` (`tier_id`), KEY `idx_sales_status` (`status`), KEY `idx_sales_date` (`object_date`), KEY `idx_sales_amount` (`amount_ht`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_structured_stock_movements` (
  `tenant_id` INT NOT NULL DEFAULT 1,
  `id` INT NOT NULL,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NULL,
  `warehouse_id` INT NULL,
  `warehouse_name` VARCHAR(190) NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `movement_type` VARCHAR(80) NULL,
  `source_type` VARCHAR(80) NULL,
  `source_id` INT NULL,
  `note` TEXT NULL,
  `movement_date` DATETIME NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(`tenant_id`, `id`),
  KEY `idx_sm_product` (`product_id`), KEY `idx_sm_warehouse` (`warehouse_id`), KEY `idx_sm_type` (`movement_type`), KEY `idx_sm_date` (`movement_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_purchase_orders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `ref` VARCHAR(90) NOT NULL,
  `supplier_id` INT NULL,
  `supplier_name` VARCHAR(190) NOT NULL,
  `order_date` DATE NULL,
  `due_date` DATE NULL,
  `status` VARCHAR(80) NOT NULL DEFAULT 'Brouillon',
  `amount_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `supplier_invoice_id` INT NULL,
  `supplier_invoice_ref` VARCHAR(90) NULL,
  `receipt_applied_at` DATETIME NULL,
  `template` VARCHAR(90) NULL,
  `note` TEXT NULL,
  `created_by` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_po_tenant_ref` (`tenant_id`, `ref`), KEY `idx_po_tenant` (`tenant_id`), KEY `idx_po_supplier` (`supplier_id`), KEY `idx_po_status` (`status`), KEY `idx_po_date` (`order_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_purchase_order_lines` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `purchase_order_id` INT NOT NULL,
  `line_no` INT NOT NULL DEFAULT 1,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NOT NULL,
  `warehouse_id` INT NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `received_qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(40) NULL,
  `pu_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `tva_rate` DECIMAL(8,3) NOT NULL DEFAULT 0,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_po_line_tenant` (`tenant_id`), KEY `idx_po_line_order` (`purchase_order_id`), KEY `idx_po_line_product` (`product_id`), KEY `idx_po_line_warehouse` (`warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_supplier_invoices` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `ref` VARCHAR(90) NOT NULL,
  `supplier_id` INT NULL,
  `supplier_name` VARCHAR(190) NOT NULL,
  `purchase_order_id` INT NULL,
  `purchase_order_ref` VARCHAR(90) NULL,
  `invoice_date` DATE NULL,
  `due_date` DATE NULL,
  `status` VARCHAR(80) NOT NULL DEFAULT 'À payer',
  `amount_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `note` TEXT NULL,
  `paid_at` DATE NULL,
  `accounting_posted_at` DATETIME NULL,
  `template` VARCHAR(90) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_si_tenant_ref` (`tenant_id`, `ref`), KEY `idx_si_tenant` (`tenant_id`), KEY `idx_si_supplier` (`supplier_id`), KEY `idx_si_status` (`status`), KEY `idx_si_due` (`due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_supplier_invoice_lines` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `supplier_invoice_id` INT NOT NULL,
  `purchase_order_line_id` INT NULL,
  `line_no` INT NOT NULL DEFAULT 1,
  `product_id` INT NULL,
  `product_ref` VARCHAR(90) NULL,
  `product_label` VARCHAR(190) NOT NULL,
  `qty` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(40) NULL,
  `pu_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `tva_rate` DECIMAL(8,3) NOT NULL DEFAULT 0,
  `total_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `total_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_si_line_tenant` (`tenant_id`), KEY `idx_si_line_invoice` (`supplier_invoice_id`), KEY `idx_si_line_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_credit_notes` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `ref` VARCHAR(90) NOT NULL,
  `invoice_id` INT NULL,
  `invoice_ref` VARCHAR(90) NULL,
  `client_id` INT NULL,
  `client_name` VARCHAR(190) NULL,
  `credit_date` DATE NULL,
  `status` VARCHAR(80) NOT NULL DEFAULT 'Brouillon',
  `amount_ht` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_tva` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `amount_ttc` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `reason` TEXT NULL,
  `note` TEXT NULL,
  `refunded_at` DATE NULL,
  `applied_at` DATETIME NULL,
  `accounting_posted_at` DATETIME NULL,
  `template` VARCHAR(90) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_cn_tenant_ref` (`tenant_id`, `ref`), KEY `idx_cn_tenant` (`tenant_id`), KEY `idx_cn_invoice` (`invoice_id`), KEY `idx_cn_status` (`status`), KEY `idx_cn_date` (`credit_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_approval_requests` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `title` VARCHAR(190) NULL,
  `object_type` VARCHAR(80) NOT NULL,
  `object_id` INT NOT NULL,
  `object_ref` VARCHAR(90) NULL,
  `requested_by` INT NULL,
  `approver_id` INT NULL,
  `status` VARCHAR(80) NOT NULL DEFAULT 'En attente',
  `amount` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `priority` VARCHAR(40) NOT NULL DEFAULT 'Normale',
  `reason` TEXT NULL,
  `decision_reason` TEXT NULL,
  `decided_by` INT NULL,
  `decided_at` DATETIME NULL,
  `applied_at` DATETIME NULL,
  `template` VARCHAR(90) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_ap_tenant` (`tenant_id`), KEY `idx_ap_object` (`object_type`, `object_id`), KEY `idx_ap_status` (`status`), KEY `idx_ap_approver` (`approver_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_approval_rules` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `object_type` VARCHAR(80) NOT NULL,
  `min_amount` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_rule_tenant` (`tenant_id`), UNIQUE KEY `uniq_rule_tenant_type` (`tenant_id`, `object_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_bank_movements` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `bank_account_id` INT NULL,
  `movement_date` DATE NULL,
  `label` VARCHAR(190) NOT NULL,
  `source_type` VARCHAR(80) NULL,
  `source_id` INT NULL,
  `debit` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `credit` DECIMAL(15,3) NOT NULL DEFAULT 0,
  `reconciled` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_bank_tenant_source` (`tenant_id`, `source_type`, `source_id`),
  KEY `idx_bank_tenant` (`tenant_id`), KEY `idx_bank_account` (`bank_account_id`), KEY `idx_bank_date` (`movement_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_api_logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `action` VARCHAR(120) NULL,
  `api_key_hash` VARCHAR(80) NULL,
  `ip` VARCHAR(80) NULL,
  `method` VARCHAR(20) NULL,
  `status_code` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_api_tenant` (`tenant_id`), KEY `idx_api_action` (`action`), KEY `idx_api_ip` (`ip`), KEY `idx_api_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ge_backups` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tenant_id` INT NOT NULL DEFAULT 1,
  `filename` VARCHAR(255) NOT NULL,
  `note` VARCHAR(255) NULL,
  `size_bytes` BIGINT NOT NULL DEFAULT 0,
  `created_by` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_backup_tenant` (`tenant_id`), KEY `idx_backup_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Default tenant and first admin
INSERT INTO `ge_tenants` (`id`,`slug`,`name`,`company_size`,`business_email`,`phone`,`country`,`city`,`zip`,`status`) VALUES (1,'global-energie','Global Energie','medium','admin@hakpoint.ma','','Maroc','Casablanca','','active') ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`), `name`=VALUES(`name`), `status`=VALUES(`status`);
INSERT INTO `ge_users` (`tenant_id`, `record_id`, `payload`, `extra_json`, `ref`, `label`, `status`, `amount`, `name`, `firstname`, `username`, `email`, `role`, `password`, `employee`, `external_user`, `force_password_change`, `twofa_enabled`, `twofa_secret`, `created_at`) VALUES (1, 1, '{"id":1,"tenant_id":1,"tenant_slug":"global-energie","ref":"USR2606-00001","name":"Admin","firstname":"Super","username":"admin","email":"admin@hakpoint.ma","role":"Administrateur","status":"Actif","employee":true,"external_user":"Interne","force_password_change":false,"twofa_enabled":false,"twofa_secret":"","password":"$2y$12$quRSbYmokZpvdKVuezufVe1Ehrki6JLdJaoVg5I3AOBu0ZYkrCAAq","created_at":"2026-06-24 00:00:00"}', '{}', 'USR2606-00001', 'Admin', 'Actif', NULL, 'Admin', 'Super', 'admin', 'admin@hakpoint.ma', 'Administrateur', '$2y$12$quRSbYmokZpvdKVuezufVe1Ehrki6JLdJaoVg5I3AOBu0ZYkrCAAq', 1, 'Interne', 0, 0, '', '2026-06-24 00:00:00') ON DUPLICATE KEY UPDATE `payload`=VALUES(`payload`), `extra_json`=VALUES(`extra_json`), `ref`=VALUES(`ref`), `label`=VALUES(`label`), `status`=VALUES(`status`), `amount`=VALUES(`amount`), `name`=VALUES(`name`), `firstname`=VALUES(`firstname`), `username`=VALUES(`username`), `email`=VALUES(`email`), `role`=VALUES(`role`), `password`=VALUES(`password`), `employee`=VALUES(`employee`), `external_user`=VALUES(`external_user`), `force_password_change`=VALUES(`force_password_change`), `twofa_enabled`=VALUES(`twofa_enabled`), `twofa_secret`=VALUES(`twofa_secret`), `created_at`=VALUES(`created_at`);
INSERT INTO `ge_settings` (`tenant_id`, `record_id`, `payload`, `extra_json`, `ref`, `label`, `status`, `amount`, `language`, `api_enabled`) VALUES (1, 1, '{"language":"fr","twofa_enabled":false,"id":1,"api_enabled":true,"api_key":"","api_allowed_origins":""}', '{}', NULL, NULL, NULL, NULL, 'fr', 1) ON DUPLICATE KEY UPDATE `payload`=VALUES(`payload`), `extra_json`=VALUES(`extra_json`), `ref`=VALUES(`ref`), `label`=VALUES(`label`), `status`=VALUES(`status`), `amount`=VALUES(`amount`), `language`=VALUES(`language`), `api_enabled`=VALUES(`api_enabled`);
INSERT INTO `ge_schema_meta` (`meta_key`,`meta_value`) VALUES ('seed_version','2026-06-26-fast-seed-v2') ON DUPLICATE KEY UPDATE `meta_value`=VALUES(`meta_value`);

SET FOREIGN_KEY_CHECKS=1;

-- Clean install: dashboard demo numbers disabled. Login after import: company code global-energie / username admin / password admin1234
