<?php require __DIR__.'/_helpers.php'; require __DIR__.'/../warehouses/_helpers.php'; $id=(int)($_GET['id']??0); $edit=$id?reception_find($id):null; $title=$edit?'Modifier réception':'Nouvelle réception'; include __DIR__.'/../layouts/header.php'; $tiers=tiers_all(); $products=data_read('products', []); $warehouses=warehouses_all(); $lines=$edit?reception_lines($id):[]; // Nouvelle réception shows only one empty line by default.
while(count($lines)<1) $lines[]=[]; ?>
<div class="dol-page shipment-page"><div class="dol-icon-title"><i class="fa-solid fa-cart-flatbed text-blue"></i></div>
<form method="post" action="index.php?page=<?=$edit?'reception_update':'reception_store'?>" class="dol-form"><?=csrf_field()?><?php if($edit): ?><input type="hidden" name="id" value="<?=$id?>"><?php endif; ?>
  <div class="dol-line"><label>Réf.</label><span class="muted"><?=e($edit['ref']??'Brouillon')?></span></div>
  <div class="dol-line"><label>Fournisseur</label><span class="field-icon"><i class="fa-solid fa-building text-purple"></i><select name="tier_id" required><option value="">Sélectionner un tiers</option><?php foreach($tiers as $t): if(($t['type']??'')!=='supplier') continue; ?><option value="<?=(int)$t['id']?>" <?=((int)($edit['tier_id']??0)===(int)$t['id'])?'selected':''?>><?=e(($t['ref']??'').' - '.($t['name']??''))?></option><?php endforeach; ?></select></span></div>
  <div class="dol-line two"><label>Date réception</label><input type="date" name="date" value="<?=e($edit['date']??date('Y-m-d'))?>"><label>Date commande</label><input type="date" name="order_date" value="<?=e($edit['order_date']??date('Y-m-d'))?>"></div>
  <div class="dol-line"><label>Entrepôt destination</label><span class="field-icon"><i class="fa-solid fa-box-open text-gold"></i><select name="warehouse_id"><?php foreach($warehouses as $w): ?><option value="<?=(int)$w['id']?>" <?=((int)($edit['warehouse_id']??0)===(int)$w['id'])?'selected':''?>><?=e($w['name']??'')?></option><?php endforeach; ?></select></span></div>
  <div class="dol-line"><label>Méthode de réception</label><select name="method"><?php foreach(['Transporteur','Livraison fournisseur','Retrait magasin','UPS','Autre'] as $m): ?><option <?=($edit['method']??'')===$m?'selected':''?>><?=e($m)?></option><?php endforeach; ?></select></div>
  <div class="dol-line"><label>Réf. fournisseur / BL</label><input name="supplier_doc" value="<?=e($edit['supplier_doc']??'')?>"></div>
  <div class="dol-line"><label>Note (publique)</label><textarea name="note_public" rows="3"><?=e($edit['note_public']??'')?></textarea></div>
  <div class="panel clean-table-box"><div class="panel-head">Lignes de réception</div><table class="clean-table"><thead><tr><th>Produit</th><th>Qté</th><th>Unité</th></tr></thead><tbody><?php foreach($lines as $l): ?><tr><td><select name="product_id[]"><option value="">Sélectionner un produit</option><?php foreach($products as $p): ?><option value="<?=(int)$p['id']?>" <?=((int)($l['product_id']??0)===(int)$p['id'])?'selected':''?>><?=e(($p['ref']??'').' - '.($p['label']??''))?></option><?php endforeach; ?></select></td><td><input type="number" name="qty[]" value="<?=e($l['qty']??0)?>" min="0" step="1"></td><td><input name="unit[]" value="<?=e($l['unit']??'u.')?>"></td></tr><?php endforeach; ?></tbody></table></div>
  <div class="dol-actions"><button class="btn orange" type="submit"><?=$edit?'ENREGISTRER':'CRÉER RÉCEPTION'?></button><a class="btn orange" href="index.php?page=receptions">ANNULER</a></div>
</form></div><?php include __DIR__.'/../layouts/footer.php'; ?>
