<?php require __DIR__.'/_helpers.php'; $title='Réceptions'; include __DIR__.'/../layouts/header.php'; $rows=receptions_all();
$q=trim($_GET['q']??''); $status=$_GET['status']??''; $from=$_GET['from']??''; $to=$_GET['to']??'';
if($q!=='') $rows=array_values(array_filter($rows,fn($r)=>stripos(($r['ref']??'').' '.($r['tier_name']??'').' '.($r['warehouse_name']??''),$q)!==false));
if($status!=='') $rows=array_values(array_filter($rows,fn($r)=>($r['status']??'')===$status));
if($from!=='') $rows=array_values(array_filter($rows,fn($r)=>($r['date']??'')>=$from));
if($to!=='') $rows=array_values(array_filter($rows,fn($r)=>($r['date']??'')<=$to));
[$rows,$rowsTotal,$rowsPage,$rowsPages]=ge_list_paginate_current($rows);
?>
<div class="clean-list-page dol-list-page">
  <?php if(!empty($_GET['error'])): ?><div class="panel" style="border-left:4px solid #ef4444;color:#991b1b;margin:12px 0;padding:10px 14px;"><?=e($_GET['error'])?></div><?php endif; ?>
  <?php if(!empty($_GET['ok']) || !empty($_GET['deleted'])): ?><div class="panel" style="border-left:4px solid #16a34a;color:#166534;margin:12px 0;padding:10px 14px;">Action effectuée avec succès.</div><?php endif; ?>
  <div class="clean-list-head"><div class="clean-title"><i class="fa-solid fa-cart-flatbed text-blue"></i><span>(<?=e($rowsTotal)?>)</span></div>
    <form id="bulkRec" action="index.php?page=reception_bulk_action" method="post" class="bulk-actions" style="display:none"><?=csrf_field()?><select name="action" required><option value="">-- Sélectionner l'action --</option><option value="Validée">Valider</option><option value="Reçue">Réceptionner et stocker</option><option value="Contrôlée">Contrôlée</option><option value="Annulée">Annuler</option><option value="delete">Supprimer</option></select><button class="btn small orange">CONFIRMER</button></form>
    <div class="clean-tools"><select class="clean-select"><option>20</option></select><span class="clean-page"><?=e($rowsPage)?> / <?=e($rowsPages)?></span><a class="clean-add" href="index.php?page=reception_new"><i class="fa-solid fa-plus"></i></a></div></div>
  <form id="recFilter" method="get"><input type="hidden" name="page" value="receptions"></form>
  <div class="clean-table-box"><table class="clean-table"><thead><tr class="clean-filters"><th><input form="recFilter" name="q" value="<?=e($q)?>" placeholder="Réf. / Fournisseur"></th><th></th><th><input form="recFilter" name="from" type="date" value="<?=e($from)?>"><input form="recFilter" name="to" type="date" value="<?=e($to)?>"></th><th><input form="recFilter" name="warehouse" placeholder="Entrepôt"></th><th><select form="recFilter" name="status"><option value=""></option><?php foreach(reception_statuses() as $s): ?><option value="<?=e($s)?>" <?=$status===$s?'selected':''?>><?=e($s)?></option><?php endforeach; ?></select></th><th class="clean-row-tools"><button form="recFilter"><i class="fa-solid fa-magnifying-glass"></i></button><a href="index.php?page=receptions"><i class="fa-solid fa-xmark"></i></a></th></tr>
  <tr><th>▾ Réf.</th><th>Fournisseur</th><th>Date réception</th><th>Entrepôt</th><th>État</th><th><i class="fa-solid fa-list"></i> <input type="checkbox" id="checkAllRec"></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><i class="fa-solid fa-cart-flatbed text-blue"></i> <a class="ref" href="index.php?page=reception_show&id=<?=(int)$r['id']?>"><?=e($r['ref']??'')?></a></td><td><?=e($r['tier_name']??'')?></td><td><?=e($r['date']??'')?></td><td><?=e($r['warehouse_name']??'')?></td><td><span class="badge <?=e(reception_status_badge($r['status']??''))?>"><?=e($r['status']??'')?></span></td><td><input form="bulkRec" class="rowCheckRec" type="checkbox" name="ids[]" value="<?=(int)$r['id']?>"></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="6" class="empty-row">Aucune réception</td></tr><?php endif; ?></tbody></table></div><?=ge_list_pager($rowsTotal,$rowsPage,$rowsPages,'p',['page'=>'receptions'])?></div>
<script>document.querySelectorAll('.rowCheckRec,#checkAllRec').forEach(el=>el.addEventListener('change',()=>{if(el.id==='checkAllRec')document.querySelectorAll('.rowCheckRec').forEach(c=>c.checked=el.checked);document.getElementById('bulkRec').style.display=document.querySelectorAll('.rowCheckRec:checked').length?'flex':'none';}));</script>
<?php include __DIR__.'/../layouts/footer.php'; ?>
