<?php require __DIR__.'/_helpers.php'; $id=(int)($_GET['id']??0); $r=reception_find($id); if(!$r) redirect_to('index.php?page=receptions'); $lines=reception_lines($id); $docs=reception_documents($id); $title=$r['ref']??'Réception'; include __DIR__.'/../layouts/header.php'; ?>
<div class="dol-detail-page"><div class="detail-tabs"><a class="active"><i class="fa-solid fa-cart-flatbed text-blue"></i> Réception</a><a href="index.php?page=reception_stats">Statistiques</a><a>Suivi</a></div>
  <div class="detail-hero"><div class="detail-icon"><i class="fa-solid fa-cart-flatbed text-blue"></i></div><div><h2><?=e($r['ref'])?></h2><p><?=e($r['tier_name'])?> · <?=e($r['warehouse_name'])?></p></div><div class="detail-right"><a href="index.php?page=receptions" class="ref">Retour liste</a><span class="badge <?=e(reception_status_badge($r['status']))?>"><?=e($r['status'])?></span></div></div>
  <?php if(!empty($_GET['error'])): ?><div class="panel" style="border-left:4px solid #ef4444;color:#991b1b;margin:12px 0;padding:10px 14px;"><?=e($_GET['error'])?></div><?php endif; ?>
  <?php if(!empty($_GET['ok'])): ?><div class="panel" style="border-left:4px solid #16a34a;color:#166534;margin:12px 0;padding:10px 14px;">Action effectuée avec succès.</div><?php endif; ?>
  <div class="two-cols"><table class="info-table"><tr><td>Fournisseur</td><td><b><?=e($r['tier_name'])?></b></td></tr><tr><td>Date réception</td><td><?=e($r['date'])?></td></tr><tr><td>Date commande</td><td><?=e($r['order_date'])?></td></tr><tr><td>Méthode de réception</td><td><?=e($r['method'])?></td></tr><tr><td>Réf. fournisseur / BL</td><td><?=e($r['supplier_doc']??'')?></td></tr></table><table class="info-table"><tr><td>Entrepôt destination</td><td><b><?=e($r['warehouse_name'])?></b></td></tr><tr><td>Nombre produits</td><td><?=reception_products_count($id)?></td></tr><tr><td>Quantité totale</td><td><?=money(reception_qty_total($id))?></td></tr><tr><td>Créé par</td><td><?=e(ge_record_author($r,'created_by'))?></td></tr><tr><td>Note</td><td><?=e($r['note_public'])?></td></tr></table></div>
  <div class="right-actions"><a class="btn orange" href="index.php?page=reception_edit&id=<?=$id?>">MODIFIER</a><a class="btn orange" href="<?=csrf_url('index.php?page=reception_status&id='.$id.'&status=Validée')?>">VALIDER</a><a class="btn orange" href="<?=csrf_url('index.php?page=reception_status&id='.$id.'&status=Reçue')?>" onclick="return confirm('Réceptionner et ajouter au stock ?')">RÉCEPTIONNER</a><a class="btn orange" href="index.php?page=reception_email&id=<?=$id?>">ENVOYER EMAIL</a><a class="btn danger-light" href="<?=csrf_url('index.php?page=reception_delete&id='.$id)?>" onclick="return confirm('Supprimer cette réception ? Le stock sera annulé si cette réception a déjà été stockée.')">SUPPRIMER</a></div>
  <div class="clean-table-box"><table class="clean-table"><thead><tr><th>Produit</th><th>Libellé</th><th>Qté reçue</th><th>Unité</th></tr></thead><tbody><?php foreach($lines as $l): ?><tr><td><i class="fa-solid fa-box text-gold"></i> <?=e($l['product_ref'])?></td><td><?=e($l['product_label'])?></td><td class="num"><?=e($l['qty'])?></td><td><?=e($l['unit'])?></td></tr><?php endforeach; if(!$lines): ?><tr><td colspan="4" class="empty-row">Aucune ligne</td></tr><?php endif; ?></tbody></table></div>
  <div class="two-cols lower-panels"><div class="panel"><div class="panel-head">Documents</div><div class="docbar"><span>Modèle de document</span><select><option>standard</option></select><a class="btn small" href="<?=csrf_url('index.php?page=reception_pdf_generate&id='.$id)?>">GÉNÉRER</a></div><table class="clean-table"><tbody><?php foreach($docs as $d): ?><tr><td><i class="fa-regular fa-file-pdf"></i> <a href="index.php?page=pdf_view&file=<?=urlencode($d['url'])?>"><?=e($d['filename'])?></a> <a class="download-pdf-icon" title="Télécharger" href="index.php?page=pdf_download&file=<?=urlencode($d['url'])?>"><i class="fa-solid fa-download text-gray"></i></a></td><td><?=e(round(($d['size']??0)/1024))?> Ko</td><td><?=e($d['created_at']??'')?></td><td><a href="<?=csrf_url('index.php?page=reception_document_delete&id='.(int)$d['id'].'&reception_id='.$id)?>" onclick="return confirm('Supprimer ce document ?')"><i class="fa-solid fa-trash"></i></a></td></tr><?php endforeach; if(!$docs): ?><tr><td>Aucun</td></tr><?php endif; ?></tbody></table></div><div class="panel"><div class="panel-head">Suivi</div><table class="clean-table"><tr><td>Créé le</td><td><?=e($r['created_at']??'')?></td></tr><tr><td>Dernière mise à jour</td><td><?=e($r['updated_at']??'')?></td></tr><tr><td>Réceptionné le</td><td><?=e($r['received_at']??'')?></td></tr></table></div></div>
</div><?php include __DIR__.'/../layouts/footer.php'; ?>
