<?php
require_permission('api.manage');
$action = $_POST['api_action'] ?? '';
try{
    if($action === 'regenerate'){
        save_app_settings([
            'api_key'=>ge_generate_api_key(),
            'api_enabled'=>true,
            'api_last_regenerated'=>date('Y-m-d H:i:s')
        ]);
        audit_log('api_key_regenerated','API key regenerated by '.ge_current_author_name());
        redirect_to('index.php?page=api&ok=regenerated');
    }
    if($action === 'toggle'){
        $enabled = !empty($_POST['api_enabled']);
        save_app_settings([
            'api_enabled'=>$enabled,
            'api_last_regenerated'=>app_setting('api_last_regenerated','')
        ]);
        audit_log('api_status_changed','API '.($enabled ? 'enabled' : 'disabled').' by '.ge_current_author_name());
        redirect_to('index.php?page=api&ok=saved');
    }
    if($action === 'origins'){
        $origins = trim((string)($_POST['api_allowed_origins'] ?? ''));
        save_app_settings(['api_allowed_origins'=>$origins]);
        audit_log('api_origins_updated','API allowed origins updated');
        redirect_to('index.php?page=api&ok=saved');
    }
}catch(Throwable $e){
    redirect_to('index.php?page=api&err='.urlencode($e->getMessage()));
}
redirect_to('index.php?page=api');
