<?php
require_once __DIR__.'/_helpers.php';
$quotes=data_read('quotes',[]); $id=(int)($_GET['id']??0); $isEdit=current_page()==='quote_edit' && $id>0; $quote=$isEdit?find_row_by_id($quotes,$id):null; if($isEdit && !$quote) redirect_to('index.php?page=quotes');
$title=$isEdit?'Modifier Devis':'Nouveau Devis'; include __DIR__.'/../layouts/header.php';
$clients=ge_available_clients(); $products=quote_products_options(); $today=date('d/m/Y');
$paymentTerms=['','50/50 Fin T','à la commande','120 j','A réception','30 jours','30 jours fin de mois','60 jours','60 jours fin de mois','A commande','A livraison','50/50','10 jours','10 jours fin de mois','15 jours','45 jours','90 jours'];
$paymentModes=['','Carte bancaire','Chèque','Espèce','Ordre de prélèvement','Virement bancaire'];
$origins=['','Bouche à oreille','Campagne Fax','Campagne Publipostage','Campagne Téléphonique','Campagne d\'emailing','Contact commercial','Contact en boutique','Employé','Incoming contact of a customer','Internet','Parrainage/Sponsoring','Partenaire'];
$deliveryDelays=['','Immédiate','1 semaine','2 semaines','3 semaines','4 weeks','5 weeks','6 weeks','8 weeks','10 weeks','12 weeks','14 weeks']; $shippingMethods=['','Generic transport service','In-Store Collection','UPS'];
function qv($k,$d=''){ global $quote; return e($quote[$k]??$d); } $action=$isEdit?'index.php?page=quote_update':'index.php?page=quote_store'; $lines=$quote['lines']??[quote_default_line()];
?>
<div class="devis-create panel dol-page">
  <div class="dol-title-icon"><i class="fa-solid fa-file-signature"></i></div>
  <form method="post" action="<?=$action?>" class="devis-form">
    <?=csrf_field()?>
    <?php if($isEdit): ?><input type="hidden" name="id" value="<?=$id?>"><?php endif; ?>
    <div class="devis-grid">
      <label>Réf.</label><div><b><?= $isEdit?e($quote['ref']):'Brouillon' ?></b></div>
      <label>Réf. client</label><input name="client_ref" value="<?=qv('client_ref')?>" class="dol-input">
      <label>Client</label><?php $selectedClientId=(int)($quote['client_id']??0); $selectedClientName=(string)($quote['client']??''); ?><div class="field-with-icons"><i class="fa-solid fa-building text-blue"></i><input type="hidden" name="client" id="quoteClientName" value="<?=e($selectedClientName)?>"><select name="client_id" class="dol-select wide" data-placeholder="Sélectionner ou taper un client" onchange="var o=this.options[this.selectedIndex];document.getElementById('quoteClientName').value=o?o.getAttribute('data-name')||'':'';"><option value="">Sélectionner un client</option><?php foreach($clients as $c): $cid=(int)($c['id']??0); $name=(string)($c['name']??''); $ref=(string)($c['ref']??''); $sel=($selectedClientId>0 && $cid===$selectedClientId) || ($selectedClientId<=0 && $selectedClientName!=='' && $selectedClientName===$name); ?><option value="<?=$cid?>" data-name="<?=e($name)?>" <?=$sel?'selected':''?>><?=e($name.($ref?' ('.$ref.')':''))?></option><?php endforeach;?></select><a class="tiny-plus" href="index.php?page=client_new">+</a></div>
      <label>Date de proposition</label><div class="inline-help"><input name="proposal_date" value="<?=qv('proposal_date',$today)?>" class="dol-input small"><small>Maintenant</small></div>
      <label>Durée de validité</label><div class="inline-help"><i class="fa-regular fa-clock"></i><input name="validity" value="<?=qv('validity','15')?>" class="dol-input xs"><span>jours</span></div>
      <label>Conditions de règlement</label><select name="payment_terms" class="dol-select"><?php foreach($paymentTerms as $o):?><option <?=($quote['payment_terms']??'')===$o?'selected':''?>><?=e($o)?></option><?php endforeach;?></select>
      <label>Mode de règlement</label><div class="field-with-icons"><i class="fa-solid fa-building-columns"></i><select name="payment_mode" class="dol-select"><?php foreach($paymentModes as $o):?><option <?=($quote['payment_mode']??'')===$o?'selected':''?>><?=e($o)?></option><?php endforeach;?></select></div>
      <label>Origine</label><div class="field-with-icons"><i class="fa-solid fa-question"></i><select name="origin" class="dol-select"><?php foreach($origins as $o):?><option <?=($quote['origin']??'')===$o?'selected':''?>><?=e($o)?></option><?php endforeach;?></select></div>
      <label>Délai de livraison (après commande)</label><div class="field-with-icons"><i class="fa-regular fa-clock"></i><select name="delivery_delay" class="dol-select"><?php foreach($deliveryDelays as $o):?><option <?=($quote['delivery_delay']??'')===$o?'selected':''?>><?=e($o)?></option><?php endforeach;?></select></div>
      <label>Méthode d'expédition</label><div class="field-with-icons"><i class="fa-solid fa-truck-fast text-cyan"></i><select name="shipping_method" class="dol-select"><?php foreach($shippingMethods as $o):?><option <?=($quote['shipping_method']??'')===$o?'selected':''?>><?=e($o)?></option><?php endforeach;?></select></div>
      <label>Date de livraison</label><div class="inline-help"><input name="delivery_date" value="<?=qv('delivery_date',$today)?>" class="dol-input small"><small>Maintenant</small></div>
      <label>Modèle de document par défaut</label><div class="field-with-icons"><i class="fa-regular fa-file-lines"></i><select name="template" class="dol-select"><option <?=qv('template','azur')==='azur'?'selected':''?>>azur</option><option <?=qv('template')==='crabe'?'selected':''?>>crabe</option></select></div>
      <label>Note (publique)</label><textarea name="public_note" class="dol-textarea"><?=qv('public_note')?></textarea>
      <label>Note (privée)</label><textarea name="private_note" class="dol-textarea"><?=qv('private_note')?></textarea>
    </div>
    <hr>
    <h3 class="section-title"><i class="fa-solid fa-list"></i> Lignes du devis</h3>
    <div class="responsive-table"><table class="edit-lines-table product-lines-editor" id="quoteLines"><thead><tr><th>Produit</th><th>Description</th><th>TVA</th><th>P.U. HT</th><th>Qté</th><th>Unité</th><th>Réduc %</th><th>Prix revient</th><th></th></tr></thead><tbody>
    <?php foreach($lines as $l): ?><tr><td><select name="line_product_id[]" class="line-product-select" data-product-line-select><option value="">Produit libre</option><?php foreach($products as $p): $pid=(int)($p['id']??0); ?><option value="<?=$pid?>" data-ref="<?=e($p['ref']??'')?>" data-label="<?=e($p['label']??'')?>" data-price="<?=e($p['sale_price']??0)?>" data-vat="<?=e($p['vat']??$p['tax_rate']??20)?>" data-cost="<?=e($p['buy_price']??$p['purchase_price']??0)?>" data-unit="<?=e($p['unit']??'u.')?>" <?=((int)($l['product_id']??0)===$pid)?'selected':''?>><?=e(trim(($p['ref']??'').' - '.($p['label']??''),' -'))?></option><?php endforeach;?></select></td><td><textarea name="line_description[]"><?=e($l['description']??'')?></textarea></td><td><input name="line_tva[]" value="<?=e($l['tva']??20)?>"></td><td><input name="line_pu_ht[]" value="<?=e($l['pu_ht']??0)?>"></td><td><input name="line_qty[]" value="<?=e($l['qty']??1)?>"></td><td><input name="line_unit[]" value="<?=e($l['unit']??'u.')?>"></td><td><input name="line_reduction[]" value="<?=e(str_replace('%','',$l['reduction']??''))?>"></td><td><input name="line_cost_price[]" value="<?=e($l['cost_price']??0)?>"></td><td><button type="button" class="small-gray-btn" onclick="this.closest('tr').remove()">×</button></td></tr><?php endforeach; ?>
    </tbody></table></div>
    <button type="button" class="small-gray-btn" onclick="addQuoteLine()"><i class="fa-solid fa-plus"></i> Ajouter une ligne</button>
    <div class="devis-actions"><button class="btn orange"><?= $isEdit?'ENREGISTRER':'CRÉER BROUILLON' ?></button><a href="index.php?page=quotes" class="btn orange">ANNULER</a></div>
  </form>
</div>
<template id="quoteLineTemplate"><tr><td><select name="line_product_id[]" class="line-product-select" data-product-line-select><option value="">Produit libre</option><?php foreach($products as $p): $pid=(int)($p['id']??0); ?><option value="<?=$pid?>" data-ref="<?=e($p['ref']??'')?>" data-label="<?=e($p['label']??'')?>" data-price="<?=e($p['sale_price']??0)?>" data-vat="<?=e($p['vat']??$p['tax_rate']??20)?>" data-cost="<?=e($p['buy_price']??$p['purchase_price']??0)?>" data-unit="<?=e($p['unit']??'u.')?>"><?=e(trim(($p['ref']??'').' - '.($p['label']??''),' -'))?></option><?php endforeach;?></select></td><td><textarea name="line_description[]"></textarea></td><td><input name="line_tva[]" value="20"></td><td><input name="line_pu_ht[]" value="0"></td><td><input name="line_qty[]" value="1"></td><td><input name="line_unit[]" value="u."></td><td><input name="line_reduction[]" value=""></td><td><input name="line_cost_price[]" value="0"></td><td><button type="button" class="small-gray-btn" onclick="this.closest('tr').remove()">×</button></td></tr></template><script>function addQuoteLine(){var t=document.getElementById('quoteLineTemplate');document.querySelector('#quoteLines tbody').appendChild(t.content.cloneNode(true)); if(window.geInitProductLineEditors) window.geInitProductLineEditors(document.querySelector('#quoteLines tbody'));}</script>
<?php include __DIR__.'/../layouts/footer.php'; ?>
