<?php
$title='Stock avancé';
$products=data_read('products',[]); $warehouses=data_read('warehouses',[]);
$productOptions=ge_erp_product_options(); $warehouseOptions=ge_erp_warehouse_options();
if(($_SERVER['REQUEST_METHOD'] ?? 'GET')==='POST'){
  require_csrf();
  $action=$_POST['action'] ?? '';
  if($action==='save_lot'){
    $lots=data_read('stock_lots',[]); $id=(int)($_POST['id']??0); $idx=-1; $old=[];
    foreach($lots as $i=>$r){ if((int)($r['id']??0)===$id){ $idx=$i; $old=$r; break; } }
    if($id<=0){ $id=next_id($lots); $old=['id'=>$id,'ref'=>'LOT'.date('ymd').'-'.str_pad((string)$id,5,'0',STR_PAD_LEFT),'created_at'=>date('Y-m-d H:i:s')]; }
    $pid=(int)($_POST['product_id']??0); $prod=ge_erp_find_collection_row('products',$pid) ?: [];
    $row=$old+[]; $row['id']=$id; $row['product_id']=$pid; $row['product_ref']=$prod['ref']??''; $row['product_label']=$prod['label']??$prod['name']??trim($_POST['product_label']??''); $row['warehouse_id']=(int)($_POST['warehouse_id']??0) ?: null; $row['lot_number']=trim($_POST['lot_number']??''); $row['expiry_date']=trim($_POST['expiry_date']??''); $row['qty']=ge_decimal($_POST['qty']??0); $row['status']=trim($_POST['status']??'Disponible'); $row['note']=trim($_POST['note']??''); $row['updated_at']=date('Y-m-d H:i:s');
    if($idx>=0) $lots[$idx]=$row; else $lots[]=$row; data_write('stock_lots',$lots,false);
    if(!empty($_POST['apply_to_stock'])) ge_stock_lot_apply_to_stock($id);
    redirect_to('index.php?page=stock_advanced&ok=lot');
  }
  if($action==='apply_lot'){ ge_stock_lot_apply_to_stock((int)($_POST['id']??0)); redirect_to('index.php?page=stock_advanced&ok=apply_lot'); }
  if($action==='delete_lot'){
    $id=(int)($_POST['id']??0); $lots=data_read('stock_lots',[]); foreach($lots as $r){ if((int)($r['id']??0)===$id && !empty($r['stock_applied_at'])) redirect_to('index.php?page=stock_advanced&err='.urlencode('Lot déjà appliqué au stock: suppression bloquée.')); }
    $lots=array_values(array_filter($lots, fn($r)=>(int)($r['id']??0)!==$id)); data_write('stock_lots',$lots,false); redirect_to('index.php?page=stock_advanced&deleted=1');
  }
  if($action==='save_serial'){
    $rows=data_read('stock_serials',[]); $id=next_id($rows); $pid=(int)($_POST['product_id']??0); $prod=ge_erp_find_collection_row('products',$pid) ?: [];
    $rows[]=['id'=>$id,'ref'=>'SER'.date('ymd').'-'.str_pad((string)$id,5,'0',STR_PAD_LEFT),'product_id'=>$pid,'product_ref'=>$prod['ref']??'','product_label'=>$prod['label']??$prod['name']??'','warehouse_id'=>(int)($_POST['warehouse_id']??0) ?: null,'serial_number'=>trim($_POST['serial_number']??''),'status'=>trim($_POST['status']??'Disponible'),'note'=>trim($_POST['note']??''),'created_at'=>date('Y-m-d H:i:s')];
    data_write('stock_serials',$rows,false); redirect_to('index.php?page=stock_advanced&ok=serial');
  }
  if($action==='delete_serial'){ $id=(int)($_POST['id']??0); $rows=array_values(array_filter(data_read('stock_serials',[]), fn($r)=>(int)($r['id']??0)!==$id)); data_write('stock_serials',$rows,false); redirect_to('index.php?page=stock_advanced&deleted=1'); }
  if($action==='save_inventory'){
    $invs=data_read('inventories',[]); $id=next_id($invs); $wid=(int)($_POST['warehouse_id']??0); $w=ge_erp_find_collection_row('warehouses',$wid) ?: [];
    $inv=['id'=>$id,'ref'=>'INVST'.date('ymd').'-'.str_pad((string)$id,5,'0',STR_PAD_LEFT),'warehouse_id'=>$wid ?: null,'warehouse_name'=>$w['name']??$w['ref']??'','date'=>trim($_POST['date']??date('Y-m-d')),'status'=>trim($_POST['status']??'Brouillon'),'note'=>trim($_POST['note']??''),'created_at'=>date('Y-m-d H:i:s')];
    $invs[]=$inv;
    $lines=data_read('inventory_lines',[]); $next=next_id($lines); $pids=(array)($_POST['inv_product_id']??[]); $counted=(array)($_POST['inv_counted_qty']??[]); $units=(array)($_POST['inv_unit']??[]); $lineNo=1;
    for($i=0;$i<count($pids);$i++){
        $pid=(int)($pids[$i]??0); if($pid<=0) continue; $prod=ge_erp_find_collection_row('products',$pid) ?: [];
        $sys=ge_erp_product_stock_at_warehouse($pid,$wid); $cnt=ge_decimal($counted[$i]??0);
        $lines[]=['id'=>$next++,'inventory_id'=>$id,'line_no'=>$lineNo++,'product_id'=>$pid,'product_ref'=>$prod['ref']??'','product_label'=>$prod['label']??$prod['name']??'','system_qty'=>$sys,'counted_qty'=>$cnt,'difference_qty'=>$cnt-$sys,'unit'=>trim($units[$i]??($prod['unit']??'u.')) ?: 'u.'];
    }
    data_write_batch(['inventories'=>$invs,'inventory_lines'=>$lines],false);
    if($inv['status']==='Appliqué' || !empty($_POST['apply_inventory'])) ge_inventory_apply_to_stock($id);
    redirect_to('index.php?page=stock_advanced&ok=inventory');
  }
  if($action==='apply_inventory'){ ge_inventory_apply_to_stock((int)($_POST['id']??0)); redirect_to('index.php?page=stock_advanced&ok=apply_inventory'); }
}
$lots=data_read('stock_lots',[]); $serials=data_read('stock_serials',[]); $inventories=data_read('inventories',[]); $inventoryLines=data_read('inventory_lines',[]);
$linesByInv=[]; foreach($inventoryLines as $l){ $linesByInv[(int)($l['inventory_id']??0)][]=$l; }
include __DIR__.'/../layouts/header.php';
?>
<div class="erp-page stock-advanced-page">
<?php if(isset($_GET['ok'])): ?><div class="email-status ok">Stock avancé mis à jour.</div><?php endif; ?><?php if(isset($_GET['err'])): ?><div class="email-status err"><?=e($_GET['err'])?></div><?php endif; ?>
<div class="erp-head"><div><h2><i class="fa-solid fa-barcode"></i> Stock avancé</h2><p>Lots, numéros de série et inventaires reliés au stock réel, aux entrepôts et aux mouvements.</p></div></div>
<div class="erp-two">
<section class="panel erp-card"><h3>Nouveau lot</h3><form method="post" class="erp-form compact-grid"><?=csrf_field()?><input type="hidden" name="action" value="save_lot"><label>Produit</label><select name="product_id" class="smart-select" required><option value="">Choisir produit</option><?php foreach($productOptions as $v=>$l): ?><option value="<?=e($v)?>"><?=e($l)?></option><?php endforeach; ?></select><label>Entrepôt</label><select name="warehouse_id" class="smart-select"><option value="">Auto</option><?php foreach($warehouseOptions as $v=>$l): ?><option value="<?=e($v)?>"><?=e($l)?></option><?php endforeach; ?></select><label>N° lot</label><input name="lot_number" required><label>Qté lot</label><input type="number" step="0.001" name="qty" required><label>Expiration</label><input type="date" name="expiry_date"><label>Statut</label><select name="status" class="smart-select"><option>Disponible</option><option>Réservé</option><option>Expiré</option><option>Bloqué</option></select><label class="checkline"><input type="checkbox" name="apply_to_stock" value="1"> Ajouter cette quantité au stock réel</label><label>Note</label><textarea name="note"></textarea><button class="btn primary">Enregistrer lot</button></form></section>
<section class="panel erp-card"><h3>Nouveau numéro de série</h3><form method="post" class="erp-form compact-grid"><?=csrf_field()?><input type="hidden" name="action" value="save_serial"><label>Produit</label><select name="product_id" class="smart-select" required><option value="">Choisir produit</option><?php foreach($productOptions as $v=>$l): ?><option value="<?=e($v)?>"><?=e($l)?></option><?php endforeach; ?></select><label>Entrepôt</label><select name="warehouse_id" class="smart-select"><option value="">Auto</option><?php foreach($warehouseOptions as $v=>$l): ?><option value="<?=e($v)?>"><?=e($l)?></option><?php endforeach; ?></select><label>Serial</label><input name="serial_number" required><label>Statut</label><select name="status" class="smart-select"><option>Disponible</option><option>Réservé</option><option>Vendu</option><option>Retourné</option><option>Bloqué</option></select><label>Note</label><textarea name="note"></textarea><button class="btn primary">Ajouter série</button></form></section>
</div>
<section class="panel erp-card"><h3>Nouvel inventaire physique</h3><form method="post" class="erp-form inventory-form"><?=csrf_field()?><input type="hidden" name="action" value="save_inventory"><div class="compact-grid"><label>Entrepôt</label><select name="warehouse_id" class="smart-select"><option value="">Stock global</option><?php foreach($warehouseOptions as $v=>$l): ?><option value="<?=e($v)?>"><?=e($l)?></option><?php endforeach; ?></select><label>Date</label><input type="date" name="date" value="<?=date('Y-m-d')?>"><label>Statut</label><select name="status" class="smart-select"><option>Brouillon</option><option>Validé</option><option>Appliqué</option><option>Annulé</option></select></div><div class="table-wrap"><table class="clean-table erp-table strong-lines inventory-lines" id="inventory-lines"><thead><tr><th>Produit</th><th>Qté comptée</th><th>Unité</th><th></th></tr></thead><tbody><tr><td><select name="inv_product_id[]" class="smart-select"><option value="">Choisir produit</option><?php foreach($productOptions as $v=>$l): ?><option value="<?=e($v)?>"><?=e($l)?></option><?php endforeach; ?></select></td><td><input type="number" step="0.001" name="inv_counted_qty[]"></td><td><input name="inv_unit[]" value="u."></td><td><button type="button" class="mini-action danger" onclick="this.closest('tr').remove()">X</button></td></tr></tbody></table></div><div class="erp-actions"><button type="button" class="btn light" onclick="geAddInventoryLine()">+ Ajouter ligne</button><label class="checkline"><input type="checkbox" name="apply_inventory" value="1"> Appliquer immédiatement au stock</label><button class="btn primary">Enregistrer inventaire</button></div><label>Note</label><textarea name="note"></textarea></form></section>
<section class="panel erp-card"><h3>Lots</h3><div class="table-wrap"><table class="clean-table erp-table strong-lines"><thead><tr><th>Produit</th><th>Lot</th><th>Entrepôt</th><th class="num">Qté</th><th>Expiration</th><th>Statut</th><th>Stock</th><th>Actions</th></tr></thead><tbody><?php foreach(array_slice(array_reverse($lots),0,20) as $r): ?><tr><td><?=e($r['product_ref']??'')?> <?=e($r['product_label']??'')?></td><td><?=e($r['lot_number']??'')?></td><td><?=e(ge_erp_get_warehouse_name((int)($r['warehouse_id']??0)))?></td><td class="num"><?=e($r['qty']??0)?></td><td><?=e(substr((string)($r['expiry_date']??''),0,10))?></td><td><span class="badge-gray"><?=e($r['status']??'')?></span></td><td><?=!empty($r['stock_applied_at'])?'<span class="badge-ok">Appliqué</span>':'<span class="badge-gray">Non appliqué</span>'?></td><td class="nowrap"><?php if(empty($r['stock_applied_at'])): ?><form method="post" style="display:inline"><?=csrf_field()?><input type="hidden" name="action" value="apply_lot"><input type="hidden" name="id" value="<?=(int)($r['id']??0)?>"><button class="mini-action success">Appliquer</button></form><?php endif; ?> <form method="post" style="display:inline" onsubmit="return confirm('Supprimer lot ?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_lot"><input type="hidden" name="id" value="<?=(int)($r['id']??0)?>"><button class="mini-action danger">Supprimer</button></form></td></tr><?php endforeach; if(!$lots): ?><tr><td colspan="8">Aucun lot.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel erp-card"><h3>Numéros de série</h3><div class="table-wrap"><table class="clean-table erp-table strong-lines"><thead><tr><th>Produit</th><th>Série</th><th>Entrepôt</th><th>Statut</th><th>Actions</th></tr></thead><tbody><?php foreach(array_slice(array_reverse($serials),0,20) as $r): ?><tr><td><?=e($r['product_ref']??'')?> <?=e($r['product_label']??'')?></td><td><?=e($r['serial_number']??'')?></td><td><?=e(ge_erp_get_warehouse_name((int)($r['warehouse_id']??0)))?></td><td><span class="badge-gray"><?=e($r['status']??'')?></span></td><td><form method="post" onsubmit="return confirm('Supprimer série ?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_serial"><input type="hidden" name="id" value="<?=(int)($r['id']??0)?>"><button class="mini-action danger">Supprimer</button></form></td></tr><?php endforeach; if(!$serials): ?><tr><td colspan="5">Aucun numéro de série.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel erp-card"><h3>Inventaires</h3><div class="table-wrap"><table class="clean-table erp-table strong-lines"><thead><tr><th>Réf.</th><th>Entrepôt</th><th>Date</th><th>Lignes</th><th>Statut</th><th>Actions</th></tr></thead><tbody><?php foreach(array_slice(array_reverse($inventories),0,20) as $r): $iid=(int)($r['id']??0); ?><tr><td><?=e($r['ref']??'')?></td><td><?=e($r['warehouse_name']??'')?></td><td><?=e(substr((string)($r['date']??''),0,10))?></td><td><?php foreach(($linesByInv[$iid]??[]) as $l): ?><div class="line-chip"><?=e($l['product_label']??'')?>: <?=e($l['counted_qty']??0)?> (diff <?=e($l['difference_qty']??0)?>)</div><?php endforeach; ?></td><td><span class="badge-gray"><?=e($r['status']??'')?></span></td><td><?php if(empty($r['applied_at'])): ?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="apply_inventory"><input type="hidden" name="id" value="<?=$iid?>"><button class="mini-action success">Appliquer au stock</button></form><?php else: ?><span class="badge-ok">Appliqué</span><?php endif; ?></td></tr><?php endforeach; if(!$inventories): ?><tr><td colspan="6">Aucun inventaire.</td></tr><?php endif; ?></tbody></table></div></section>
</div>
<script>
function geAddInventoryLine(){const tbody=document.querySelector('#inventory-lines tbody'); if(!tbody) return; const tr=tbody.querySelector('tr').cloneNode(true); tr.querySelectorAll('input').forEach(i=>{ if(i.name.includes('inv_unit')) i.value='u.'; else i.value=''; }); tr.querySelectorAll('select').forEach(s=>s.selectedIndex=0); tbody.appendChild(tr);}
</script>
<?php include __DIR__.'/../layouts/footer.php'; ?>
